export const FETCH_FLOWERS_REQUEST = "FETCH_FLOWERS_REQUEST";
export const FETCH_FLOWERS_SUCCESS = "FETCH_FLOWERS_SUCCESS";
export const FETCH_FLOWERS_FAILURE = "FETCH_FLOWERS_FAILURE";

export const FETCH_SEARCH_FLOWERS = "FETCH_SEARCH_FLOWERS";
